# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/uncommonde4th/Projects/Coursework_SP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/uncommonde4th/Projects/Coursework_SP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/uncommonde4th/Projects/Coursework_SP/CMakeFiles /home/uncommonde4th/Projects/Coursework_SP//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/uncommonde4th/Projects/Coursework_SP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sysdb

# Build rule for target.
sysdb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sysdb
.PHONY : sysdb

# fast build rule for target.
sysdb/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sysdb.dir/build.make CMakeFiles/sysdb.dir/build
.PHONY : sysdb/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sysdb.dir/build.make CMakeFiles/sysdb.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sysdb.dir/build.make CMakeFiles/sysdb.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sysdb.dir/build.make CMakeFiles/sysdb.dir/main.cpp.s
.PHONY : main.cpp.s

src/btree/src/bplus_tree.o: src/btree/src/bplus_tree.cpp.o
.PHONY : src/btree/src/bplus_tree.o

# target to build an object file
src/btree/src/bplus_tree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sysdb.dir/build.make CMakeFiles/sysdb.dir/src/btree/src/bplus_tree.cpp.o
.PHONY : src/btree/src/bplus_tree.cpp.o

src/btree/src/bplus_tree.i: src/btree/src/bplus_tree.cpp.i
.PHONY : src/btree/src/bplus_tree.i

# target to preprocess a source file
src/btree/src/bplus_tree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sysdb.dir/build.make CMakeFiles/sysdb.dir/src/btree/src/bplus_tree.cpp.i
.PHONY : src/btree/src/bplus_tree.cpp.i

src/btree/src/bplus_tree.s: src/btree/src/bplus_tree.cpp.s
.PHONY : src/btree/src/bplus_tree.s

# target to generate assembly for a file
src/btree/src/bplus_tree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sysdb.dir/build.make CMakeFiles/sysdb.dir/src/btree/src/bplus_tree.cpp.s
.PHONY : src/btree/src/bplus_tree.cpp.s

src/record/src/heap_file.o: src/record/src/heap_file.cpp.o
.PHONY : src/record/src/heap_file.o

# target to build an object file
src/record/src/heap_file.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sysdb.dir/build.make CMakeFiles/sysdb.dir/src/record/src/heap_file.cpp.o
.PHONY : src/record/src/heap_file.cpp.o

src/record/src/heap_file.i: src/record/src/heap_file.cpp.i
.PHONY : src/record/src/heap_file.i

# target to preprocess a source file
src/record/src/heap_file.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sysdb.dir/build.make CMakeFiles/sysdb.dir/src/record/src/heap_file.cpp.i
.PHONY : src/record/src/heap_file.cpp.i

src/record/src/heap_file.s: src/record/src/heap_file.cpp.s
.PHONY : src/record/src/heap_file.s

# target to generate assembly for a file
src/record/src/heap_file.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sysdb.dir/build.make CMakeFiles/sysdb.dir/src/record/src/heap_file.cpp.s
.PHONY : src/record/src/heap_file.cpp.s

src/record/src/page.o: src/record/src/page.cpp.o
.PHONY : src/record/src/page.o

# target to build an object file
src/record/src/page.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sysdb.dir/build.make CMakeFiles/sysdb.dir/src/record/src/page.cpp.o
.PHONY : src/record/src/page.cpp.o

src/record/src/page.i: src/record/src/page.cpp.i
.PHONY : src/record/src/page.i

# target to preprocess a source file
src/record/src/page.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sysdb.dir/build.make CMakeFiles/sysdb.dir/src/record/src/page.cpp.i
.PHONY : src/record/src/page.cpp.i

src/record/src/page.s: src/record/src/page.cpp.s
.PHONY : src/record/src/page.s

# target to generate assembly for a file
src/record/src/page.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sysdb.dir/build.make CMakeFiles/sysdb.dir/src/record/src/page.cpp.s
.PHONY : src/record/src/page.cpp.s

src/record/src/record_manager.o: src/record/src/record_manager.cpp.o
.PHONY : src/record/src/record_manager.o

# target to build an object file
src/record/src/record_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sysdb.dir/build.make CMakeFiles/sysdb.dir/src/record/src/record_manager.cpp.o
.PHONY : src/record/src/record_manager.cpp.o

src/record/src/record_manager.i: src/record/src/record_manager.cpp.i
.PHONY : src/record/src/record_manager.i

# target to preprocess a source file
src/record/src/record_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sysdb.dir/build.make CMakeFiles/sysdb.dir/src/record/src/record_manager.cpp.i
.PHONY : src/record/src/record_manager.cpp.i

src/record/src/record_manager.s: src/record/src/record_manager.cpp.s
.PHONY : src/record/src/record_manager.s

# target to generate assembly for a file
src/record/src/record_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sysdb.dir/build.make CMakeFiles/sysdb.dir/src/record/src/record_manager.cpp.s
.PHONY : src/record/src/record_manager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sysdb"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/btree/src/bplus_tree.o"
	@echo "... src/btree/src/bplus_tree.i"
	@echo "... src/btree/src/bplus_tree.s"
	@echo "... src/record/src/heap_file.o"
	@echo "... src/record/src/heap_file.i"
	@echo "... src/record/src/heap_file.s"
	@echo "... src/record/src/page.o"
	@echo "... src/record/src/page.i"
	@echo "... src/record/src/page.s"
	@echo "... src/record/src/record_manager.o"
	@echo "... src/record/src/record_manager.i"
	@echo "... src/record/src/record_manager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

